language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t chukwurado/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true chukwurado/docker-react npm run test